### ISSUE TITLE
Does TOAD work with other filesystems (e.g. ext2, exfat)?

### ISSUE THREAD

**Issue by carlosfilhoadm** [ajacoutot/toad#3]
Hi,

Thank you for this tool, it's useful and simple to use.

Assuming I have installed e2fsprogs and exfat-fuse, will TOAD work with those other filesystems?

Thanks.

**Comment by ajacoutot** [comment]
Hi @carlosfilhoadm 
toad should already work with ext2 and fat32 (not extended).
It doesn't yet have support for fuse or extra features with e2fsprogs but that something that can be considered.

**Comment by carlosfilhoadm** [comment]
Thank you @ajacoutot

Would you kindly consider adding support for these other filesystems in the future?

That would really help those of us who have to interact with other operating systems.

Thank you again for this tool.

**Comment by finkfox** [comment]
It would be great to see this feature in the next release.
I created a simple pull request #4. Maybe it can be of help.
Thank you for your work @ajacoutot.

**Comment by ajacoutot** [comment]
Thanks @finkfox 
I merged it and will keep playing with it without issuing a new release.
